/*
 * Allegro REST API
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.allegro.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import pl.wtx.allegro.api.client.model.AutomaticPricingRuleConfigurationChangeByAmountChangeByAmount;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.allegro.api.client.invoker.JSON;

/**
 * AutomaticPricingRuleConfigurationChangeByAmount
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class AutomaticPricingRuleConfigurationChangeByAmount {
  public static final String SERIALIZED_NAME_CHANGE_BY_AMOUNT = "changeByAmount";
  @SerializedName(SERIALIZED_NAME_CHANGE_BY_AMOUNT)
  @javax.annotation.Nonnull
  private AutomaticPricingRuleConfigurationChangeByAmountChangeByAmount changeByAmount;

  public AutomaticPricingRuleConfigurationChangeByAmount() {
  }

  public AutomaticPricingRuleConfigurationChangeByAmount changeByAmount(@javax.annotation.Nonnull AutomaticPricingRuleConfigurationChangeByAmountChangeByAmount changeByAmount) {
    this.changeByAmount = changeByAmount;
    return this;
  }

  /**
   * Get changeByAmount
   * @return changeByAmount
   */
  @javax.annotation.Nonnull
  public AutomaticPricingRuleConfigurationChangeByAmountChangeByAmount getChangeByAmount() {
    return changeByAmount;
  }

  public void setChangeByAmount(@javax.annotation.Nonnull AutomaticPricingRuleConfigurationChangeByAmountChangeByAmount changeByAmount) {
    this.changeByAmount = changeByAmount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutomaticPricingRuleConfigurationChangeByAmount automaticPricingRuleConfigurationChangeByAmount = (AutomaticPricingRuleConfigurationChangeByAmount) o;
    return Objects.equals(this.changeByAmount, automaticPricingRuleConfigurationChangeByAmount.changeByAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changeByAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutomaticPricingRuleConfigurationChangeByAmount {\n");
    sb.append("    changeByAmount: ").append(toIndentedString(changeByAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("changeByAmount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("changeByAmount");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AutomaticPricingRuleConfigurationChangeByAmount
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AutomaticPricingRuleConfigurationChangeByAmount.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AutomaticPricingRuleConfigurationChangeByAmount is not found in the empty JSON string", AutomaticPricingRuleConfigurationChangeByAmount.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AutomaticPricingRuleConfigurationChangeByAmount.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AutomaticPricingRuleConfigurationChangeByAmount` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AutomaticPricingRuleConfigurationChangeByAmount.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `changeByAmount`
      AutomaticPricingRuleConfigurationChangeByAmountChangeByAmount.validateJsonElement(jsonObj.get("changeByAmount"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AutomaticPricingRuleConfigurationChangeByAmount.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AutomaticPricingRuleConfigurationChangeByAmount' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AutomaticPricingRuleConfigurationChangeByAmount> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AutomaticPricingRuleConfigurationChangeByAmount.class));

       return (TypeAdapter<T>) new TypeAdapter<AutomaticPricingRuleConfigurationChangeByAmount>() {
           @Override
           public void write(JsonWriter out, AutomaticPricingRuleConfigurationChangeByAmount value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AutomaticPricingRuleConfigurationChangeByAmount read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AutomaticPricingRuleConfigurationChangeByAmount given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AutomaticPricingRuleConfigurationChangeByAmount
   * @throws IOException if the JSON string is invalid with respect to AutomaticPricingRuleConfigurationChangeByAmount
   */
  public static AutomaticPricingRuleConfigurationChangeByAmount fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AutomaticPricingRuleConfigurationChangeByAmount.class);
  }

  /**
   * Convert an instance of AutomaticPricingRuleConfigurationChangeByAmount to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

