/*
 * Allegro REST API
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.allegro.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import pl.wtx.allegro.api.client.model.AvailablePromotionPackage;
import pl.wtx.allegro.api.client.model.MarketplaceAvailablePromotionPackages;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.allegro.api.client.invoker.JSON;

/**
 * AvailablePromotionPackages
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class AvailablePromotionPackages {
  public static final String SERIALIZED_NAME_MARKETPLACE_ID = "marketplaceId";
  @SerializedName(SERIALIZED_NAME_MARKETPLACE_ID)
  @javax.annotation.Nullable
  private String marketplaceId;

  public static final String SERIALIZED_NAME_BASE_PACKAGES = "basePackages";
  @SerializedName(SERIALIZED_NAME_BASE_PACKAGES)
  @javax.annotation.Nullable
  private List<AvailablePromotionPackage> basePackages = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXTRA_PACKAGES = "extraPackages";
  @SerializedName(SERIALIZED_NAME_EXTRA_PACKAGES)
  @javax.annotation.Nullable
  private List<AvailablePromotionPackage> extraPackages = new ArrayList<>();

  public static final String SERIALIZED_NAME_ADDITIONAL_MARKETPLACES = "additionalMarketplaces";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_MARKETPLACES)
  @javax.annotation.Nullable
  private List<MarketplaceAvailablePromotionPackages> additionalMarketplaces = new ArrayList<>();

  public AvailablePromotionPackages() {
  }

  public AvailablePromotionPackages marketplaceId(@javax.annotation.Nullable String marketplaceId) {
    this.marketplaceId = marketplaceId;
    return this;
  }

  /**
   * Get marketplaceId
   * @return marketplaceId
   */
  @javax.annotation.Nullable
  public String getMarketplaceId() {
    return marketplaceId;
  }

  public void setMarketplaceId(@javax.annotation.Nullable String marketplaceId) {
    this.marketplaceId = marketplaceId;
  }


  public AvailablePromotionPackages basePackages(@javax.annotation.Nullable List<AvailablePromotionPackage> basePackages) {
    this.basePackages = basePackages;
    return this;
  }

  public AvailablePromotionPackages addBasePackagesItem(AvailablePromotionPackage basePackagesItem) {
    if (this.basePackages == null) {
      this.basePackages = new ArrayList<>();
    }
    this.basePackages.add(basePackagesItem);
    return this;
  }

  /**
   * Available base promotion packages. Only one base package can be set on an offer.
   * @return basePackages
   */
  @javax.annotation.Nullable
  public List<AvailablePromotionPackage> getBasePackages() {
    return basePackages;
  }

  public void setBasePackages(@javax.annotation.Nullable List<AvailablePromotionPackage> basePackages) {
    this.basePackages = basePackages;
  }


  public AvailablePromotionPackages extraPackages(@javax.annotation.Nullable List<AvailablePromotionPackage> extraPackages) {
    this.extraPackages = extraPackages;
    return this;
  }

  public AvailablePromotionPackages addExtraPackagesItem(AvailablePromotionPackage extraPackagesItem) {
    if (this.extraPackages == null) {
      this.extraPackages = new ArrayList<>();
    }
    this.extraPackages.add(extraPackagesItem);
    return this;
  }

  /**
   * Available extra promotion packages. Multiple different extra packages can be set on an offer.
   * @return extraPackages
   */
  @javax.annotation.Nullable
  public List<AvailablePromotionPackage> getExtraPackages() {
    return extraPackages;
  }

  public void setExtraPackages(@javax.annotation.Nullable List<AvailablePromotionPackage> extraPackages) {
    this.extraPackages = extraPackages;
  }


  public AvailablePromotionPackages additionalMarketplaces(@javax.annotation.Nullable List<MarketplaceAvailablePromotionPackages> additionalMarketplaces) {
    this.additionalMarketplaces = additionalMarketplaces;
    return this;
  }

  public AvailablePromotionPackages addAdditionalMarketplacesItem(MarketplaceAvailablePromotionPackages additionalMarketplacesItem) {
    if (this.additionalMarketplaces == null) {
      this.additionalMarketplaces = new ArrayList<>();
    }
    this.additionalMarketplaces.add(additionalMarketplacesItem);
    return this;
  }

  /**
   * Available promotion packages on additional marketplaces.
   * @return additionalMarketplaces
   */
  @javax.annotation.Nullable
  public List<MarketplaceAvailablePromotionPackages> getAdditionalMarketplaces() {
    return additionalMarketplaces;
  }

  public void setAdditionalMarketplaces(@javax.annotation.Nullable List<MarketplaceAvailablePromotionPackages> additionalMarketplaces) {
    this.additionalMarketplaces = additionalMarketplaces;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvailablePromotionPackages availablePromotionPackages = (AvailablePromotionPackages) o;
    return Objects.equals(this.marketplaceId, availablePromotionPackages.marketplaceId) &&
        Objects.equals(this.basePackages, availablePromotionPackages.basePackages) &&
        Objects.equals(this.extraPackages, availablePromotionPackages.extraPackages) &&
        Objects.equals(this.additionalMarketplaces, availablePromotionPackages.additionalMarketplaces);
  }

  @Override
  public int hashCode() {
    return Objects.hash(marketplaceId, basePackages, extraPackages, additionalMarketplaces);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvailablePromotionPackages {\n");
    sb.append("    marketplaceId: ").append(toIndentedString(marketplaceId)).append("\n");
    sb.append("    basePackages: ").append(toIndentedString(basePackages)).append("\n");
    sb.append("    extraPackages: ").append(toIndentedString(extraPackages)).append("\n");
    sb.append("    additionalMarketplaces: ").append(toIndentedString(additionalMarketplaces)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("marketplaceId");
    openapiFields.add("basePackages");
    openapiFields.add("extraPackages");
    openapiFields.add("additionalMarketplaces");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AvailablePromotionPackages
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AvailablePromotionPackages.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AvailablePromotionPackages is not found in the empty JSON string", AvailablePromotionPackages.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AvailablePromotionPackages.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AvailablePromotionPackages` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("marketplaceId") != null && !jsonObj.get("marketplaceId").isJsonNull()) && !jsonObj.get("marketplaceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `marketplaceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("marketplaceId").toString()));
      }
      if (jsonObj.get("basePackages") != null && !jsonObj.get("basePackages").isJsonNull()) {
        JsonArray jsonArraybasePackages = jsonObj.getAsJsonArray("basePackages");
        if (jsonArraybasePackages != null) {
          // ensure the json data is an array
          if (!jsonObj.get("basePackages").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `basePackages` to be an array in the JSON string but got `%s`", jsonObj.get("basePackages").toString()));
          }

          // validate the optional field `basePackages` (array)
          for (int i = 0; i < jsonArraybasePackages.size(); i++) {
            AvailablePromotionPackage.validateJsonElement(jsonArraybasePackages.get(i));
          };
        }
      }
      if (jsonObj.get("extraPackages") != null && !jsonObj.get("extraPackages").isJsonNull()) {
        JsonArray jsonArrayextraPackages = jsonObj.getAsJsonArray("extraPackages");
        if (jsonArrayextraPackages != null) {
          // ensure the json data is an array
          if (!jsonObj.get("extraPackages").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `extraPackages` to be an array in the JSON string but got `%s`", jsonObj.get("extraPackages").toString()));
          }

          // validate the optional field `extraPackages` (array)
          for (int i = 0; i < jsonArrayextraPackages.size(); i++) {
            AvailablePromotionPackage.validateJsonElement(jsonArrayextraPackages.get(i));
          };
        }
      }
      if (jsonObj.get("additionalMarketplaces") != null && !jsonObj.get("additionalMarketplaces").isJsonNull()) {
        JsonArray jsonArrayadditionalMarketplaces = jsonObj.getAsJsonArray("additionalMarketplaces");
        if (jsonArrayadditionalMarketplaces != null) {
          // ensure the json data is an array
          if (!jsonObj.get("additionalMarketplaces").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `additionalMarketplaces` to be an array in the JSON string but got `%s`", jsonObj.get("additionalMarketplaces").toString()));
          }

          // validate the optional field `additionalMarketplaces` (array)
          for (int i = 0; i < jsonArrayadditionalMarketplaces.size(); i++) {
            MarketplaceAvailablePromotionPackages.validateJsonElement(jsonArrayadditionalMarketplaces.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AvailablePromotionPackages.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AvailablePromotionPackages' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AvailablePromotionPackages> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AvailablePromotionPackages.class));

       return (TypeAdapter<T>) new TypeAdapter<AvailablePromotionPackages>() {
           @Override
           public void write(JsonWriter out, AvailablePromotionPackages value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AvailablePromotionPackages read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AvailablePromotionPackages given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AvailablePromotionPackages
   * @throws IOException if the JSON string is invalid with respect to AvailablePromotionPackages
   */
  public static AvailablePromotionPackages fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AvailablePromotionPackages.class);
  }

  /**
   * Convert an instance of AvailablePromotionPackages to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

