/*
 * Allegro REST API
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.allegro.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import pl.wtx.allegro.api.client.model.CheckoutFormFulfillmentShipmentSummaryLineItemsSent;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.allegro.api.client.invoker.JSON;

/**
 * CheckoutFormFulfillmentShipmentSummary
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class CheckoutFormFulfillmentShipmentSummary {
  public static final String SERIALIZED_NAME_LINE_ITEMS_SENT = "lineItemsSent";
  @SerializedName(SERIALIZED_NAME_LINE_ITEMS_SENT)
  @javax.annotation.Nullable
  private CheckoutFormFulfillmentShipmentSummaryLineItemsSent lineItemsSent;

  public CheckoutFormFulfillmentShipmentSummary() {
  }

  public CheckoutFormFulfillmentShipmentSummary lineItemsSent(@javax.annotation.Nullable CheckoutFormFulfillmentShipmentSummaryLineItemsSent lineItemsSent) {
    this.lineItemsSent = lineItemsSent;
    return this;
  }

  /**
   * Get lineItemsSent
   * @return lineItemsSent
   */
  @javax.annotation.Nullable
  public CheckoutFormFulfillmentShipmentSummaryLineItemsSent getLineItemsSent() {
    return lineItemsSent;
  }

  public void setLineItemsSent(@javax.annotation.Nullable CheckoutFormFulfillmentShipmentSummaryLineItemsSent lineItemsSent) {
    this.lineItemsSent = lineItemsSent;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckoutFormFulfillmentShipmentSummary checkoutFormFulfillmentShipmentSummary = (CheckoutFormFulfillmentShipmentSummary) o;
    return Objects.equals(this.lineItemsSent, checkoutFormFulfillmentShipmentSummary.lineItemsSent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lineItemsSent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckoutFormFulfillmentShipmentSummary {\n");
    sb.append("    lineItemsSent: ").append(toIndentedString(lineItemsSent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("lineItemsSent");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CheckoutFormFulfillmentShipmentSummary
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CheckoutFormFulfillmentShipmentSummary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CheckoutFormFulfillmentShipmentSummary is not found in the empty JSON string", CheckoutFormFulfillmentShipmentSummary.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CheckoutFormFulfillmentShipmentSummary.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CheckoutFormFulfillmentShipmentSummary` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `lineItemsSent`
      if (jsonObj.get("lineItemsSent") != null && !jsonObj.get("lineItemsSent").isJsonNull()) {
        CheckoutFormFulfillmentShipmentSummaryLineItemsSent.validateJsonElement(jsonObj.get("lineItemsSent"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CheckoutFormFulfillmentShipmentSummary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CheckoutFormFulfillmentShipmentSummary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CheckoutFormFulfillmentShipmentSummary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CheckoutFormFulfillmentShipmentSummary.class));

       return (TypeAdapter<T>) new TypeAdapter<CheckoutFormFulfillmentShipmentSummary>() {
           @Override
           public void write(JsonWriter out, CheckoutFormFulfillmentShipmentSummary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CheckoutFormFulfillmentShipmentSummary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CheckoutFormFulfillmentShipmentSummary given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CheckoutFormFulfillmentShipmentSummary
   * @throws IOException if the JSON string is invalid with respect to CheckoutFormFulfillmentShipmentSummary
   */
  public static CheckoutFormFulfillmentShipmentSummary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CheckoutFormFulfillmentShipmentSummary.class);
  }

  /**
   * Convert an instance of CheckoutFormFulfillmentShipmentSummary to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

