/*
 * Allegro REST API
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.allegro.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import pl.wtx.allegro.api.client.model.OfferPromoOption;
import pl.wtx.allegro.api.client.model.OfferPromoOptionsPendingChanges;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.allegro.api.client.invoker.JSON;

/**
 * MarketplaceOfferPromoOption
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class MarketplaceOfferPromoOption {
  public static final String SERIALIZED_NAME_MARKETPLACE_ID = "marketplaceId";
  @SerializedName(SERIALIZED_NAME_MARKETPLACE_ID)
  @javax.annotation.Nullable
  private String marketplaceId;

  public static final String SERIALIZED_NAME_BASE_PACKAGE = "basePackage";
  @SerializedName(SERIALIZED_NAME_BASE_PACKAGE)
  @javax.annotation.Nullable
  private OfferPromoOption basePackage;

  public static final String SERIALIZED_NAME_EXTRA_PACKAGES = "extraPackages";
  @SerializedName(SERIALIZED_NAME_EXTRA_PACKAGES)
  @javax.annotation.Nullable
  private List<OfferPromoOption> extraPackages = new ArrayList<>();

  public static final String SERIALIZED_NAME_PENDING_CHANGES = "pendingChanges";
  @SerializedName(SERIALIZED_NAME_PENDING_CHANGES)
  @javax.annotation.Nullable
  private OfferPromoOptionsPendingChanges pendingChanges;

  public MarketplaceOfferPromoOption() {
  }

  public MarketplaceOfferPromoOption marketplaceId(@javax.annotation.Nullable String marketplaceId) {
    this.marketplaceId = marketplaceId;
    return this;
  }

  /**
   * Get marketplaceId
   * @return marketplaceId
   */
  @javax.annotation.Nullable
  public String getMarketplaceId() {
    return marketplaceId;
  }

  public void setMarketplaceId(@javax.annotation.Nullable String marketplaceId) {
    this.marketplaceId = marketplaceId;
  }


  public MarketplaceOfferPromoOption basePackage(@javax.annotation.Nullable OfferPromoOption basePackage) {
    this.basePackage = basePackage;
    return this;
  }

  /**
   * Get basePackage
   * @return basePackage
   */
  @javax.annotation.Nullable
  public OfferPromoOption getBasePackage() {
    return basePackage;
  }

  public void setBasePackage(@javax.annotation.Nullable OfferPromoOption basePackage) {
    this.basePackage = basePackage;
  }


  public MarketplaceOfferPromoOption extraPackages(@javax.annotation.Nullable List<OfferPromoOption> extraPackages) {
    this.extraPackages = extraPackages;
    return this;
  }

  public MarketplaceOfferPromoOption addExtraPackagesItem(OfferPromoOption extraPackagesItem) {
    if (this.extraPackages == null) {
      this.extraPackages = new ArrayList<>();
    }
    this.extraPackages.add(extraPackagesItem);
    return this;
  }

  /**
   * Extra promotion packages set on offer.
   * @return extraPackages
   */
  @javax.annotation.Nullable
  public List<OfferPromoOption> getExtraPackages() {
    return extraPackages;
  }

  public void setExtraPackages(@javax.annotation.Nullable List<OfferPromoOption> extraPackages) {
    this.extraPackages = extraPackages;
  }


  public MarketplaceOfferPromoOption pendingChanges(@javax.annotation.Nullable OfferPromoOptionsPendingChanges pendingChanges) {
    this.pendingChanges = pendingChanges;
    return this;
  }

  /**
   * Get pendingChanges
   * @return pendingChanges
   */
  @javax.annotation.Nullable
  public OfferPromoOptionsPendingChanges getPendingChanges() {
    return pendingChanges;
  }

  public void setPendingChanges(@javax.annotation.Nullable OfferPromoOptionsPendingChanges pendingChanges) {
    this.pendingChanges = pendingChanges;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketplaceOfferPromoOption marketplaceOfferPromoOption = (MarketplaceOfferPromoOption) o;
    return Objects.equals(this.marketplaceId, marketplaceOfferPromoOption.marketplaceId) &&
        Objects.equals(this.basePackage, marketplaceOfferPromoOption.basePackage) &&
        Objects.equals(this.extraPackages, marketplaceOfferPromoOption.extraPackages) &&
        Objects.equals(this.pendingChanges, marketplaceOfferPromoOption.pendingChanges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(marketplaceId, basePackage, extraPackages, pendingChanges);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketplaceOfferPromoOption {\n");
    sb.append("    marketplaceId: ").append(toIndentedString(marketplaceId)).append("\n");
    sb.append("    basePackage: ").append(toIndentedString(basePackage)).append("\n");
    sb.append("    extraPackages: ").append(toIndentedString(extraPackages)).append("\n");
    sb.append("    pendingChanges: ").append(toIndentedString(pendingChanges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("marketplaceId");
    openapiFields.add("basePackage");
    openapiFields.add("extraPackages");
    openapiFields.add("pendingChanges");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MarketplaceOfferPromoOption
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MarketplaceOfferPromoOption.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MarketplaceOfferPromoOption is not found in the empty JSON string", MarketplaceOfferPromoOption.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MarketplaceOfferPromoOption.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MarketplaceOfferPromoOption` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("marketplaceId") != null && !jsonObj.get("marketplaceId").isJsonNull()) && !jsonObj.get("marketplaceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `marketplaceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("marketplaceId").toString()));
      }
      // validate the optional field `basePackage`
      if (jsonObj.get("basePackage") != null && !jsonObj.get("basePackage").isJsonNull()) {
        OfferPromoOption.validateJsonElement(jsonObj.get("basePackage"));
      }
      if (jsonObj.get("extraPackages") != null && !jsonObj.get("extraPackages").isJsonNull()) {
        JsonArray jsonArrayextraPackages = jsonObj.getAsJsonArray("extraPackages");
        if (jsonArrayextraPackages != null) {
          // ensure the json data is an array
          if (!jsonObj.get("extraPackages").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `extraPackages` to be an array in the JSON string but got `%s`", jsonObj.get("extraPackages").toString()));
          }

          // validate the optional field `extraPackages` (array)
          for (int i = 0; i < jsonArrayextraPackages.size(); i++) {
            OfferPromoOption.validateJsonElement(jsonArrayextraPackages.get(i));
          };
        }
      }
      // validate the optional field `pendingChanges`
      if (jsonObj.get("pendingChanges") != null && !jsonObj.get("pendingChanges").isJsonNull()) {
        OfferPromoOptionsPendingChanges.validateJsonElement(jsonObj.get("pendingChanges"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MarketplaceOfferPromoOption.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MarketplaceOfferPromoOption' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MarketplaceOfferPromoOption> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MarketplaceOfferPromoOption.class));

       return (TypeAdapter<T>) new TypeAdapter<MarketplaceOfferPromoOption>() {
           @Override
           public void write(JsonWriter out, MarketplaceOfferPromoOption value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MarketplaceOfferPromoOption read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MarketplaceOfferPromoOption given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MarketplaceOfferPromoOption
   * @throws IOException if the JSON string is invalid with respect to MarketplaceOfferPromoOption
   */
  public static MarketplaceOfferPromoOption fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MarketplaceOfferPromoOption.class);
  }

  /**
   * Convert an instance of MarketplaceOfferPromoOption to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

