/*
 * Allegro REST API
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.allegro.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.allegro.api.client.invoker.JSON;

/**
 * Information about offer&#39;s business properties.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class OfferListingDtoV1B2b {
  public static final String SERIALIZED_NAME_BUYABLE_ONLY_BY_BUSINESS = "buyableOnlyByBusiness";
  @SerializedName(SERIALIZED_NAME_BUYABLE_ONLY_BY_BUSINESS)
  @javax.annotation.Nullable
  private Boolean buyableOnlyByBusiness;

  public OfferListingDtoV1B2b() {
  }

  public OfferListingDtoV1B2b buyableOnlyByBusiness(@javax.annotation.Nullable Boolean buyableOnlyByBusiness) {
    this.buyableOnlyByBusiness = buyableOnlyByBusiness;
    return this;
  }

  /**
   * Get buyableOnlyByBusiness
   * @return buyableOnlyByBusiness
   */
  @javax.annotation.Nullable
  public Boolean getBuyableOnlyByBusiness() {
    return buyableOnlyByBusiness;
  }

  public void setBuyableOnlyByBusiness(@javax.annotation.Nullable Boolean buyableOnlyByBusiness) {
    this.buyableOnlyByBusiness = buyableOnlyByBusiness;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferListingDtoV1B2b offerListingDtoV1B2b = (OfferListingDtoV1B2b) o;
    return Objects.equals(this.buyableOnlyByBusiness, offerListingDtoV1B2b.buyableOnlyByBusiness);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buyableOnlyByBusiness);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferListingDtoV1B2b {\n");
    sb.append("    buyableOnlyByBusiness: ").append(toIndentedString(buyableOnlyByBusiness)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("buyableOnlyByBusiness");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OfferListingDtoV1B2b
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OfferListingDtoV1B2b.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OfferListingDtoV1B2b is not found in the empty JSON string", OfferListingDtoV1B2b.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OfferListingDtoV1B2b.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OfferListingDtoV1B2b` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OfferListingDtoV1B2b.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OfferListingDtoV1B2b' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OfferListingDtoV1B2b> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OfferListingDtoV1B2b.class));

       return (TypeAdapter<T>) new TypeAdapter<OfferListingDtoV1B2b>() {
           @Override
           public void write(JsonWriter out, OfferListingDtoV1B2b value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OfferListingDtoV1B2b read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OfferListingDtoV1B2b given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OfferListingDtoV1B2b
   * @throws IOException if the JSON string is invalid with respect to OfferListingDtoV1B2b
   */
  public static OfferListingDtoV1B2b fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OfferListingDtoV1B2b.class);
  }

  /**
   * Convert an instance of OfferListingDtoV1B2b to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

