/*
 * Allegro REST API
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.allegro.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.allegro.api.client.invoker.JSON;

/**
 * Promo options on base marketplace.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class Promotion {
  public static final String SERIALIZED_NAME_EMPHASIZED1D = "emphasized1d";
  @SerializedName(SERIALIZED_NAME_EMPHASIZED1D)
  @javax.annotation.Nullable
  private Boolean emphasized1d;

  public static final String SERIALIZED_NAME_EMPHASIZED10D = "emphasized10d";
  @SerializedName(SERIALIZED_NAME_EMPHASIZED10D)
  @javax.annotation.Nullable
  private Boolean emphasized10d;

  public static final String SERIALIZED_NAME_PROMO_PACKAGE = "promoPackage";
  @SerializedName(SERIALIZED_NAME_PROMO_PACKAGE)
  @javax.annotation.Nullable
  private Boolean promoPackage;

  public static final String SERIALIZED_NAME_DEPARTMENT_PAGE = "departmentPage";
  @SerializedName(SERIALIZED_NAME_DEPARTMENT_PAGE)
  @javax.annotation.Nullable
  private Boolean departmentPage;

  public Promotion() {
  }

  public Promotion emphasized1d(@javax.annotation.Nullable Boolean emphasized1d) {
    this.emphasized1d = emphasized1d;
    return this;
  }

  /**
   * Get emphasized1d
   * @return emphasized1d
   */
  @javax.annotation.Nullable
  public Boolean getEmphasized1d() {
    return emphasized1d;
  }

  public void setEmphasized1d(@javax.annotation.Nullable Boolean emphasized1d) {
    this.emphasized1d = emphasized1d;
  }


  public Promotion emphasized10d(@javax.annotation.Nullable Boolean emphasized10d) {
    this.emphasized10d = emphasized10d;
    return this;
  }

  /**
   * Get emphasized10d
   * @return emphasized10d
   */
  @javax.annotation.Nullable
  public Boolean getEmphasized10d() {
    return emphasized10d;
  }

  public void setEmphasized10d(@javax.annotation.Nullable Boolean emphasized10d) {
    this.emphasized10d = emphasized10d;
  }


  public Promotion promoPackage(@javax.annotation.Nullable Boolean promoPackage) {
    this.promoPackage = promoPackage;
    return this;
  }

  /**
   * Get promoPackage
   * @return promoPackage
   */
  @javax.annotation.Nullable
  public Boolean getPromoPackage() {
    return promoPackage;
  }

  public void setPromoPackage(@javax.annotation.Nullable Boolean promoPackage) {
    this.promoPackage = promoPackage;
  }


  public Promotion departmentPage(@javax.annotation.Nullable Boolean departmentPage) {
    this.departmentPage = departmentPage;
    return this;
  }

  /**
   * Get departmentPage
   * @return departmentPage
   */
  @javax.annotation.Nullable
  public Boolean getDepartmentPage() {
    return departmentPage;
  }

  public void setDepartmentPage(@javax.annotation.Nullable Boolean departmentPage) {
    this.departmentPage = departmentPage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Promotion promotion = (Promotion) o;
    return Objects.equals(this.emphasized1d, promotion.emphasized1d) &&
        Objects.equals(this.emphasized10d, promotion.emphasized10d) &&
        Objects.equals(this.promoPackage, promotion.promoPackage) &&
        Objects.equals(this.departmentPage, promotion.departmentPage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emphasized1d, emphasized10d, promoPackage, departmentPage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Promotion {\n");
    sb.append("    emphasized1d: ").append(toIndentedString(emphasized1d)).append("\n");
    sb.append("    emphasized10d: ").append(toIndentedString(emphasized10d)).append("\n");
    sb.append("    promoPackage: ").append(toIndentedString(promoPackage)).append("\n");
    sb.append("    departmentPage: ").append(toIndentedString(departmentPage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("emphasized1d");
    openapiFields.add("emphasized10d");
    openapiFields.add("promoPackage");
    openapiFields.add("departmentPage");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Promotion
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Promotion.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Promotion is not found in the empty JSON string", Promotion.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Promotion.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Promotion` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Promotion.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Promotion' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Promotion> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Promotion.class));

       return (TypeAdapter<T>) new TypeAdapter<Promotion>() {
           @Override
           public void write(JsonWriter out, Promotion value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Promotion read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Promotion given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Promotion
   * @throws IOException if the JSON string is invalid with respect to Promotion
   */
  public static Promotion fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Promotion.class);
  }

  /**
   * Convert an instance of Promotion to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

