/*
 * Allegro REST API
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.allegro.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import pl.wtx.allegro.api.client.model.ResponsibleProducerAddress;
import pl.wtx.allegro.api.client.model.ResponsibleProducerContact;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.allegro.api.client.invoker.JSON;

/**
 * Responsible producer data.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class ResponsibleProducerResponseProducerData {
  public static final String SERIALIZED_NAME_TRADE_NAME = "tradeName";
  @SerializedName(SERIALIZED_NAME_TRADE_NAME)
  @javax.annotation.Nullable
  private String tradeName;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  @javax.annotation.Nullable
  private ResponsibleProducerAddress address;

  public static final String SERIALIZED_NAME_CONTACT = "contact";
  @SerializedName(SERIALIZED_NAME_CONTACT)
  @javax.annotation.Nullable
  private ResponsibleProducerContact contact;

  public ResponsibleProducerResponseProducerData() {
  }

  public ResponsibleProducerResponseProducerData tradeName(@javax.annotation.Nullable String tradeName) {
    this.tradeName = tradeName;
    return this;
  }

  /**
   * Name of company, first name and last name or trade name of company responsible for producing product.
   * @return tradeName
   */
  @javax.annotation.Nullable
  public String getTradeName() {
    return tradeName;
  }

  public void setTradeName(@javax.annotation.Nullable String tradeName) {
    this.tradeName = tradeName;
  }


  public ResponsibleProducerResponseProducerData address(@javax.annotation.Nullable ResponsibleProducerAddress address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  public ResponsibleProducerAddress getAddress() {
    return address;
  }

  public void setAddress(@javax.annotation.Nullable ResponsibleProducerAddress address) {
    this.address = address;
  }


  public ResponsibleProducerResponseProducerData contact(@javax.annotation.Nullable ResponsibleProducerContact contact) {
    this.contact = contact;
    return this;
  }

  /**
   * Get contact
   * @return contact
   */
  @javax.annotation.Nullable
  public ResponsibleProducerContact getContact() {
    return contact;
  }

  public void setContact(@javax.annotation.Nullable ResponsibleProducerContact contact) {
    this.contact = contact;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsibleProducerResponseProducerData responsibleProducerResponseProducerData = (ResponsibleProducerResponseProducerData) o;
    return Objects.equals(this.tradeName, responsibleProducerResponseProducerData.tradeName) &&
        Objects.equals(this.address, responsibleProducerResponseProducerData.address) &&
        Objects.equals(this.contact, responsibleProducerResponseProducerData.contact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tradeName, address, contact);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponsibleProducerResponseProducerData {\n");
    sb.append("    tradeName: ").append(toIndentedString(tradeName)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tradeName");
    openapiFields.add("address");
    openapiFields.add("contact");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResponsibleProducerResponseProducerData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResponsibleProducerResponseProducerData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ResponsibleProducerResponseProducerData is not found in the empty JSON string", ResponsibleProducerResponseProducerData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResponsibleProducerResponseProducerData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ResponsibleProducerResponseProducerData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("tradeName") != null && !jsonObj.get("tradeName").isJsonNull()) && !jsonObj.get("tradeName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tradeName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tradeName").toString()));
      }
      // validate the optional field `address`
      if (jsonObj.get("address") != null && !jsonObj.get("address").isJsonNull()) {
        ResponsibleProducerAddress.validateJsonElement(jsonObj.get("address"));
      }
      // validate the optional field `contact`
      if (jsonObj.get("contact") != null && !jsonObj.get("contact").isJsonNull()) {
        ResponsibleProducerContact.validateJsonElement(jsonObj.get("contact"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResponsibleProducerResponseProducerData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResponsibleProducerResponseProducerData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResponsibleProducerResponseProducerData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResponsibleProducerResponseProducerData.class));

       return (TypeAdapter<T>) new TypeAdapter<ResponsibleProducerResponseProducerData>() {
           @Override
           public void write(JsonWriter out, ResponsibleProducerResponseProducerData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResponsibleProducerResponseProducerData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResponsibleProducerResponseProducerData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResponsibleProducerResponseProducerData
   * @throws IOException if the JSON string is invalid with respect to ResponsibleProducerResponseProducerData
   */
  public static ResponsibleProducerResponseProducerData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResponsibleProducerResponseProducerData.class);
  }

  /**
   * Convert an instance of ResponsibleProducerResponseProducerData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

