/*
 * Allegro REST API
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.allegro.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import pl.wtx.allegro.api.client.model.RestrictionCause;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.allegro.api.client.invoker.JSON;

/**
 * ReturnPolicyAvailability
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class ReturnPolicyAvailability {
  /**
   * Indicates if return policy is full, restricted or disabled.
   */
  @JsonAdapter(RangeEnum.Adapter.class)
  public enum RangeEnum {
    FULL("FULL"),
    
    RESTRICTED("RESTRICTED"),
    
    DISABLED("DISABLED");

    private String value;

    RangeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RangeEnum fromValue(String value) {
      for (RangeEnum b : RangeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RangeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RangeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RangeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return RangeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      RangeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_RANGE = "range";
  @SerializedName(SERIALIZED_NAME_RANGE)
  @javax.annotation.Nonnull
  private RangeEnum range;

  public static final String SERIALIZED_NAME_RESTRICTION_CAUSE = "restrictionCause";
  @SerializedName(SERIALIZED_NAME_RESTRICTION_CAUSE)
  @javax.annotation.Nullable
  private RestrictionCause restrictionCause;

  public ReturnPolicyAvailability() {
  }

  public ReturnPolicyAvailability range(@javax.annotation.Nonnull RangeEnum range) {
    this.range = range;
    return this;
  }

  /**
   * Indicates if return policy is full, restricted or disabled.
   * @return range
   */
  @javax.annotation.Nonnull
  public RangeEnum getRange() {
    return range;
  }

  public void setRange(@javax.annotation.Nonnull RangeEnum range) {
    this.range = range;
  }


  public ReturnPolicyAvailability restrictionCause(@javax.annotation.Nullable RestrictionCause restrictionCause) {
    this.restrictionCause = restrictionCause;
    return this;
  }

  /**
   * Get restrictionCause
   * @return restrictionCause
   */
  @javax.annotation.Nullable
  public RestrictionCause getRestrictionCause() {
    return restrictionCause;
  }

  public void setRestrictionCause(@javax.annotation.Nullable RestrictionCause restrictionCause) {
    this.restrictionCause = restrictionCause;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReturnPolicyAvailability returnPolicyAvailability = (ReturnPolicyAvailability) o;
    return Objects.equals(this.range, returnPolicyAvailability.range) &&
        Objects.equals(this.restrictionCause, returnPolicyAvailability.restrictionCause);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(range, restrictionCause);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReturnPolicyAvailability {\n");
    sb.append("    range: ").append(toIndentedString(range)).append("\n");
    sb.append("    restrictionCause: ").append(toIndentedString(restrictionCause)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("range");
    openapiFields.add("restrictionCause");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("range");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ReturnPolicyAvailability
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReturnPolicyAvailability.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReturnPolicyAvailability is not found in the empty JSON string", ReturnPolicyAvailability.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ReturnPolicyAvailability.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ReturnPolicyAvailability` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ReturnPolicyAvailability.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("range").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `range` to be a primitive type in the JSON string but got `%s`", jsonObj.get("range").toString()));
      }
      // validate the required field `range`
      RangeEnum.validateJsonElement(jsonObj.get("range"));
      // validate the optional field `restrictionCause`
      if (jsonObj.get("restrictionCause") != null && !jsonObj.get("restrictionCause").isJsonNull()) {
        RestrictionCause.validateJsonElement(jsonObj.get("restrictionCause"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReturnPolicyAvailability.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReturnPolicyAvailability' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReturnPolicyAvailability> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReturnPolicyAvailability.class));

       return (TypeAdapter<T>) new TypeAdapter<ReturnPolicyAvailability>() {
           @Override
           public void write(JsonWriter out, ReturnPolicyAvailability value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReturnPolicyAvailability read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ReturnPolicyAvailability given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ReturnPolicyAvailability
   * @throws IOException if the JSON string is invalid with respect to ReturnPolicyAvailability
   */
  public static ReturnPolicyAvailability fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReturnPolicyAvailability.class);
  }

  /**
   * Convert an instance of ReturnPolicyAvailability to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

