/*
 * Allegro REST API
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.allegro.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.allegro.api.client.invoker.JSON;

/**
 * Details about charged storage fee. Only present in case of CHARGED status, null otherwise.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class StockStorageFeeDetails {
  public static final String SERIALIZED_NAME_FEE_PAYABLE_AT = "feePayableAt";
  @SerializedName(SERIALIZED_NAME_FEE_PAYABLE_AT)
  @javax.annotation.Nullable
  private String feePayableAt;

  public static final String SERIALIZED_NAME_CHARGED_ITEMS_QUANTITY = "chargedItemsQuantity";
  @SerializedName(SERIALIZED_NAME_CHARGED_ITEMS_QUANTITY)
  @javax.annotation.Nullable
  private BigDecimal chargedItemsQuantity;

  public static final String SERIALIZED_NAME_AMOUNT_GROSS = "amountGross";
  @SerializedName(SERIALIZED_NAME_AMOUNT_GROSS)
  @javax.annotation.Nullable
  private BigDecimal amountGross;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  @javax.annotation.Nullable
  private String currency;

  public StockStorageFeeDetails() {
  }

  public StockStorageFeeDetails feePayableAt(@javax.annotation.Nullable String feePayableAt) {
    this.feePayableAt = feePayableAt;
    return this;
  }

  /**
   * Predicted date when the fee will be charged based on quantity and average sales. Only present in case of PREDICTION status, null otherwise.
   * @return feePayableAt
   */
  @javax.annotation.Nullable
  public String getFeePayableAt() {
    return feePayableAt;
  }

  public void setFeePayableAt(@javax.annotation.Nullable String feePayableAt) {
    this.feePayableAt = feePayableAt;
  }


  public StockStorageFeeDetails chargedItemsQuantity(@javax.annotation.Nullable BigDecimal chargedItemsQuantity) {
    this.chargedItemsQuantity = chargedItemsQuantity;
    return this;
  }

  /**
   * Number of items, for which storage fee was charged. For example seller might have 20 items in total, but only 3 of them are stored longer than free storage period, so the fee is applied only for them.
   * @return chargedItemsQuantity
   */
  @javax.annotation.Nullable
  public BigDecimal getChargedItemsQuantity() {
    return chargedItemsQuantity;
  }

  public void setChargedItemsQuantity(@javax.annotation.Nullable BigDecimal chargedItemsQuantity) {
    this.chargedItemsQuantity = chargedItemsQuantity;
  }


  public StockStorageFeeDetails amountGross(@javax.annotation.Nullable BigDecimal amountGross) {
    this.amountGross = amountGross;
    return this;
  }

  /**
   * Total gross amount of the charged fee.
   * @return amountGross
   */
  @javax.annotation.Nullable
  public BigDecimal getAmountGross() {
    return amountGross;
  }

  public void setAmountGross(@javax.annotation.Nullable BigDecimal amountGross) {
    this.amountGross = amountGross;
  }


  public StockStorageFeeDetails currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Currency in which the fee was charged.
   * @return currency
   */
  @javax.annotation.Nullable
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StockStorageFeeDetails stockStorageFeeDetails = (StockStorageFeeDetails) o;
    return Objects.equals(this.feePayableAt, stockStorageFeeDetails.feePayableAt) &&
        Objects.equals(this.chargedItemsQuantity, stockStorageFeeDetails.chargedItemsQuantity) &&
        Objects.equals(this.amountGross, stockStorageFeeDetails.amountGross) &&
        Objects.equals(this.currency, stockStorageFeeDetails.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feePayableAt, chargedItemsQuantity, amountGross, currency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StockStorageFeeDetails {\n");
    sb.append("    feePayableAt: ").append(toIndentedString(feePayableAt)).append("\n");
    sb.append("    chargedItemsQuantity: ").append(toIndentedString(chargedItemsQuantity)).append("\n");
    sb.append("    amountGross: ").append(toIndentedString(amountGross)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("feePayableAt");
    openapiFields.add("chargedItemsQuantity");
    openapiFields.add("amountGross");
    openapiFields.add("currency");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StockStorageFeeDetails
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StockStorageFeeDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in StockStorageFeeDetails is not found in the empty JSON string", StockStorageFeeDetails.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StockStorageFeeDetails.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `StockStorageFeeDetails` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("feePayableAt") != null && !jsonObj.get("feePayableAt").isJsonNull()) && !jsonObj.get("feePayableAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `feePayableAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("feePayableAt").toString()));
      }
      if ((jsonObj.get("currency") != null && !jsonObj.get("currency").isJsonNull()) && !jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StockStorageFeeDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StockStorageFeeDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StockStorageFeeDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StockStorageFeeDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<StockStorageFeeDetails>() {
           @Override
           public void write(JsonWriter out, StockStorageFeeDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StockStorageFeeDetails read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StockStorageFeeDetails given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StockStorageFeeDetails
   * @throws IOException if the JSON string is invalid with respect to StockStorageFeeDetails
   */
  public static StockStorageFeeDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StockStorageFeeDetails.class);
  }

  /**
   * Convert an instance of StockStorageFeeDetails to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

