/*
 * Allegro REST API
 * https://developer.allegro.pl/about  Documentation is generated from [this OpenAPI 3.0 specification file](https://developer.allegro.pl/swagger.yaml). To start working with our API, you can also check our [official Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api) in Postman.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.allegro.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.allegro.api.client.invoker.JSON;

/**
 * Represents selling stats of given product in merchant&#39;s stock.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class StockSellingStats {
  public static final String SERIALIZED_NAME_LAST_WEEK_AVERAGE = "lastWeekAverage";
  @SerializedName(SERIALIZED_NAME_LAST_WEEK_AVERAGE)
  @javax.annotation.Nullable
  private BigDecimal lastWeekAverage;

  public static final String SERIALIZED_NAME_LAST_THIRTY_DAYS_SUM = "lastThirtyDaysSum";
  @SerializedName(SERIALIZED_NAME_LAST_THIRTY_DAYS_SUM)
  @javax.annotation.Nullable
  private BigDecimal lastThirtyDaysSum;

  public StockSellingStats() {
  }

  public StockSellingStats lastWeekAverage(@javax.annotation.Nullable BigDecimal lastWeekAverage) {
    this.lastWeekAverage = lastWeekAverage;
    return this;
  }

  /**
   * Moving daily sales average calculated for last week (7 calendar days before current day), rounded to integer using \&quot;half up\&quot; logic. Doesn&#39;t include sales for current day. Note that this number is not stable and might change between subsequent requests due to e.g. cancellations of orders within the calculation period.
   * @return lastWeekAverage
   */
  @javax.annotation.Nullable
  public BigDecimal getLastWeekAverage() {
    return lastWeekAverage;
  }

  public void setLastWeekAverage(@javax.annotation.Nullable BigDecimal lastWeekAverage) {
    this.lastWeekAverage = lastWeekAverage;
  }


  public StockSellingStats lastThirtyDaysSum(@javax.annotation.Nullable BigDecimal lastThirtyDaysSum) {
    this.lastThirtyDaysSum = lastThirtyDaysSum;
    return this;
  }

  /**
   * Total sales for the last 30 calendar days. Doesn&#39;t include sales for current day. Note that this number is not stable and might change between subsequent requests due to e.g. cancellations of orders within the calculation period.
   * @return lastThirtyDaysSum
   */
  @javax.annotation.Nullable
  public BigDecimal getLastThirtyDaysSum() {
    return lastThirtyDaysSum;
  }

  public void setLastThirtyDaysSum(@javax.annotation.Nullable BigDecimal lastThirtyDaysSum) {
    this.lastThirtyDaysSum = lastThirtyDaysSum;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StockSellingStats stockSellingStats = (StockSellingStats) o;
    return Objects.equals(this.lastWeekAverage, stockSellingStats.lastWeekAverage) &&
        Objects.equals(this.lastThirtyDaysSum, stockSellingStats.lastThirtyDaysSum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastWeekAverage, lastThirtyDaysSum);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StockSellingStats {\n");
    sb.append("    lastWeekAverage: ").append(toIndentedString(lastWeekAverage)).append("\n");
    sb.append("    lastThirtyDaysSum: ").append(toIndentedString(lastThirtyDaysSum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("lastWeekAverage");
    openapiFields.add("lastThirtyDaysSum");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StockSellingStats
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StockSellingStats.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in StockSellingStats is not found in the empty JSON string", StockSellingStats.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StockSellingStats.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `StockSellingStats` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StockSellingStats.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StockSellingStats' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StockSellingStats> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StockSellingStats.class));

       return (TypeAdapter<T>) new TypeAdapter<StockSellingStats>() {
           @Override
           public void write(JsonWriter out, StockSellingStats value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StockSellingStats read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StockSellingStats given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StockSellingStats
   * @throws IOException if the JSON string is invalid with respect to StockSellingStats
   */
  public static StockSellingStats fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StockSellingStats.class);
  }

  /**
   * Convert an instance of StockSellingStats to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

